- hosts: localhost
  connection: local
  become: true

  pre-tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
